trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration production 
  displayName: 'npm install and build'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '.'
    skip_app_build: true
    azure_static_web_apps_api_token: $(AzureStaticWebAppApiToken) 
