# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --configuration production 
  displayName: 'npm install and build'
  
  # 5. Deploy naar Static Web App (Azure CLI)
- task: AzureCLI@2
  inputs:
    azureSubscription: 'GezelligTijdAzureConnection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az staticwebapp upload --name "GezelligTijdClient" \
      --resource-group "gezelligtijd_recource" \
      --source dist/GezelligTijdClient 

- task: AzureStaticWebApp@0
  inputs:
    app_location: 'dist/GezelligTijdClient' 
    skip_app_build: true
    azure_static_web_apps_api_token: $(AzureStaticWebAppApiToken)